version: "2"

services:
  data:
    image: tianon/true
    volumes:
      - ./database:/var/lib/mysql

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mysql:5.7
    volumes_from:
      - data
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

